export const acostarImages = [
    {
        id: 1,
        type: "image",
        src: "/commercialGallery/acostar4.jpg",
        alt: "Commercial Image 1",
        span: "col-span-8 aspect-[16/9] max-sm:col-span-12",
    },
    {
        id: 2,
        type: "image",
        src: "/commercialGallery/acostar1.jpg",
        alt: "Commercial Image 2",
        span: "col-span-4",
    },
    {
        id: 3,
        type: "image",
        src: "/commercialGallery/acostar6.jpg",
        alt: "Commercial Image 3",
        span: "col-span-4",
    },
    {
        id: 4,
        type: "image",
        src: "/commercialGallery/acostar5.jpg",
        alt: "Commercial Image 4",
        span: "col-span-4",
    },
    {
        id: 5,
        type: "image",
        src: "/commercialGallery/acostar2.jpg",
        alt: "Commercial Image 5",
        span: "col-span-4",
    },
    {
        id: 6,
        type: "image",
        src: "/commercialGallery/acostar3.jpg",
        alt: "Commercial Image 6",
        span: "col-span-4",
    },
    {
        id: 7,
        type: "image",
        src: "/commercialGallery/acostar7.jpg",
        alt: "Commercial Image 7",
        span: "col-span-4",
    },
];
