export const dayonestudioImages = [
    {
        id: 1,
        type: "image",
        src: "/commercialGallery/dayonestudio-1.jpg",
        alt: "Commercial Image 1",
        span: "col-span-4",
    },
    {
        id: 2,
        type: "image",
        src: "/commercialGallery/dayonestudio-2.jpg",
        alt: "Commercial Image 2",
        span: "col-span-4",
    },
    {
        id: 3,
        type: "image",
        src: "/commercialGallery/dayonestudio-3.jpg",
        alt: "Commercial Image 3",
        span: "col-span-4",
    },
    {
        id: 4,
        type: "image",
        src: "/commercialGallery/dayonestudio-4.jpg",
        alt: "Commercial Image 4",
        span: "col-span-4",
    },
    {
        id: 5,
        type: "image",
        src: "/commercialGallery/dayonestudio-5.jpg",
        alt: "Commercial Image 5",
        span: "col-span-4",
    },
    {
        id: 6,
        type: "image",
        src: "/commercialGallery/dayonestudio-6.jpg",
        alt: "Commercial Image 6",
        span: "col-span-4",
    },
    {
        id: 7,
        type: "image",
        src: "/commercialGallery/dayonestudio-7.jpg",
        alt: "Commercial Image 7",
        span: "col-span-4",
    },
];
