export const dreamworksAutoImages = [
    {
        id: 1,
        type: "image",
        src: "/commercialGallery/Dreamworks Auto/DSC09862.webp",
        alt: "Dreamworks Auto Image 1",
        span: "col-span-8 aspect-[16/12] max-sm:col-span-12",
    },
    {
        id: 2,
        type: "video",
        src: "/commercialGallery/Dreamworks Auto/Dreamworks Green M3 Reel.webm",
        alt: "Dreamworks Auto Video 1",
        span: "col-span-4",
    },
    {
        id: 3,
        type: "image",
        src: "/commercialGallery/Dreamworks Auto/DSC00004.webp",
        alt: "Dreamworks Auto Image 2",
        span: "col-span-4",
    },
    {
        id: 4,
        type: "image",
        src: "/commercialGallery/Dreamworks Auto/DSC00024.webp",
        alt: "Dreamworks Auto Image 3",
        span: "col-span-4",
    },
    {
        id: 5,
        type: "image",
        src: "/commercialGallery/Dreamworks Auto/DSC00037.webp",
        alt: "Dreamworks Auto Image 4",
        span: "col-span-4",
    },
    {
        id: 6,
        type: "video",
        src: "/commercialGallery/Dreamworks Auto/Dreamworks Red M4.webm",
        alt: "Dreamworks Auto Video 2",
        span: "col-span-6",
    },
    {
        id: 7,
        type: "image",
        src: "/commercialGallery/Dreamworks Auto/DSC00428.webp",
        alt: "Dreamworks Auto Image 5",
        span: "col-span-6",
    },
    {
        id: 9,
        type: "image",
        src: "/commercialGallery/Dreamworks Auto/DSC00439.webp",
        alt: "Dreamworks Auto Image 6",
        span: "col-span-6",
    },
    {
        id: 10,
        type: "image",
        src: "/commercialGallery/Dreamworks Auto/DSC00470.webp",
        alt: "Dreamworks Auto Image 7",
        span: "col-span-4",
    },
    {
        id: 11,
        type: "image",
        src: "/commercialGallery/Dreamworks Auto/DSC00475.webp",
        alt: "Dreamworks Auto Image 8",
        span: "col-span-4",
    },
    {
        id: 12,
        type: "image",
        src: "/commercialGallery/Dreamworks Auto/DSC00488.webp",
        alt: "Dreamworks Auto Image 9",
        span: "col-span-4",
    },
    {
        id: 13,
        type: "image",
        src: "/commercialGallery/Dreamworks Auto/DSC00503.webp",
        alt: "Dreamworks Auto Image 10",
        span: "col-span-4",
    },
    {
        id: 14,
        type: "image",
        src: "/commercialGallery/Dreamworks Auto/DSC00541.webp",
        alt: "Dreamworks Auto Image 11",
        span: "col-span-4",
    },
    {
        id: 16,
        type: "image",
        src: "/commercialGallery/Dreamworks Auto/DSC01319.webp",
        alt: "Dreamworks Auto Image 13",
        span: "col-span-4",
    },
    {
        id: 17,
        type: "image",
        src: "/commercialGallery/Dreamworks Auto/DSC01325.webp",
        alt: "Dreamworks Auto Image 14",
        span: "col-span-4",
    },
    {
        id: 15,
        type: "image",
        src: "/commercialGallery/Dreamworks Auto/DSC00547.webp",
        alt: "Dreamworks Auto Image 12",
        span: "col-span-9 aspect-[16/9] max-sm:col-span-12",
    },
    {
        id: 8,
        type: "video",
        src: "/commercialGallery/Dreamworks Auto/PCZ M4.webm",
        alt: "Dreamworks Auto Video 3",
        span: "col-span-3",
    },
];
