export const pakenhamcarcoImages = [
    {
        id: 1,
        type: "image",
        src: "/commercialGallery/PakenhamCarco/DSC02121.webp",
        alt: "Commercial Image 1",
        span: "col-span-8 aspect-[16/9] max-sm:col-span-12",
    },
    {
        id: 2,
        type: "image",
        src: "/commercialGallery/PakenhamCarco/DSC02157.webp",
        alt: "Commercial Image 2",
        span: "col-span-6",
    },
    {
        id: 3,
        type: "image",
        src: "/commercialGallery/PakenhamCarco/DSC02127.webp",
        alt: "Commercial Image 3",
        span: "col-span-6 row-span-2",
    },
    {
        id: 4,
        type: "image",
        src: "/commercialGallery/PakenhamCarco/DSC02142.webp",
        alt: "Commercial Image 4",
        span: "col-span-6",
    },
    {
        id: 5,
        type: "image",
        src: "/commercialGallery/PakenhamCarco/DSC02123.webp",
        alt: "Commercial Image 5",
        span: "col-span-4",
    },
    {
        id: 6,
        type: "image",
        src: "/commercialGallery/PakenhamCarco/DSC02134.webp",
        alt: "Commercial Image 6",
        span: "col-span-4",
    },
    {
        id: 7,
        type: "image",
        src: "/commercialGallery/PakenhamCarco/DSC02102.webp",
        alt: "Commercial Image 7",
        span: "col-span-4",
    },
];
